"""friends tables

Revision ID: 2c8af57065b3
Revises: faa458ecb3b5
Create Date: 2026-01-19 17:24:13.841240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8af57065b3'
down_revision: Union[str, None] = 'faa458ecb3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), server_default='1', nullable=False),
    sa.Column('uses_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_invites_code'), 'friend_invites', ['code'], unique=True)
    op.create_index(op.f('ix_friend_invites_created_by_user_id'), 'friend_invites', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_friend_invites_expires_at'), 'friend_invites', ['expires_at'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_low_id', sa.UUID(), nullable=False),
    sa.Column('user_high_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_low_id <> user_high_id', name='ck_friendships_not_self'),
    sa.ForeignKeyConstraint(['user_high_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_low_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_low_id', 'user_high_id', name='uq_friendships_pair')
    )
    op.create_index(op.f('ix_friendships_user_high_id'), 'friendships', ['user_high_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_low_id'), 'friendships', ['user_low_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_user_low_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_high_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_invites_expires_at'), table_name='friend_invites')
    op.drop_index(op.f('ix_friend_invites_created_by_user_id'), table_name='friend_invites')
    op.drop_index(op.f('ix_friend_invites_code'), table_name='friend_invites')
    op.drop_table('friend_invites')
    # ### end Alembic commands ###
