"""titles and watchlist items

Revision ID: 505d008ab2b5
Revises: 7920c84c9c6c
Create Date: 2026-01-20 21:00:48.523613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '505d008ab2b5'
down_revision: Union[str, None] = '7920c84c9c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_titles_media_type', table_name='titles')
    op.drop_index('ix_titles_release_year', table_name='titles')
    op.drop_index('ix_titles_source', table_name='titles')
    op.drop_index('ix_titles_source_id', table_name='titles')
    op.drop_constraint('uq_titles_source_sourceid_mediatype', 'titles', type_='unique')
    op.create_index('ix_titles_source_source_id', 'titles', ['source', 'source_id'], unique=False)
    op.create_unique_constraint('uq_titles_source_source_id_media_type', 'titles', ['source', 'source_id', 'media_type'])
    op.drop_column('titles', 'updated_at')
    op.drop_column('titles', 'original_name')
    op.drop_index('ix_watchlist_items_added_by_user_id', table_name='watchlist_items')
    op.drop_index('ix_watchlist_items_snoozed_until', table_name='watchlist_items')
    op.drop_index('ix_watchlist_items_status', table_name='watchlist_items')
    op.create_index('ix_watchlist_items_group_snoozed', 'watchlist_items', ['group_id', 'snoozed_until'], unique=False)
    op.create_index('ix_watchlist_items_group_status', 'watchlist_items', ['group_id', 'status'], unique=False)
    op.drop_constraint('watchlist_items_title_id_fkey', 'watchlist_items', type_='foreignkey')
    op.drop_constraint('watchlist_items_group_id_fkey', 'watchlist_items', type_='foreignkey')
    op.drop_constraint('watchlist_items_added_by_user_id_fkey', 'watchlist_items', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist_items', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'watchlist_items', 'titles', ['title_id'], ['id'])
    op.drop_column('watchlist_items', 'added_by_user_id')
    op.drop_column('watchlist_items', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('watchlist_items', sa.Column('added_by_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'watchlist_items', type_='foreignkey')
    op.drop_constraint(None, 'watchlist_items', type_='foreignkey')
    op.create_foreign_key('watchlist_items_added_by_user_id_fkey', 'watchlist_items', 'users', ['added_by_user_id'], ['id'])
    op.create_foreign_key('watchlist_items_group_id_fkey', 'watchlist_items', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('watchlist_items_title_id_fkey', 'watchlist_items', 'titles', ['title_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_watchlist_items_group_status', table_name='watchlist_items')
    op.drop_index('ix_watchlist_items_group_snoozed', table_name='watchlist_items')
    op.create_index('ix_watchlist_items_status', 'watchlist_items', ['status'], unique=False)
    op.create_index('ix_watchlist_items_snoozed_until', 'watchlist_items', ['snoozed_until'], unique=False)
    op.create_index('ix_watchlist_items_added_by_user_id', 'watchlist_items', ['added_by_user_id'], unique=False)
    op.add_column('titles', sa.Column('original_name', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('titles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_titles_source_source_id_media_type', 'titles', type_='unique')
    op.drop_index('ix_titles_source_source_id', table_name='titles')
    op.create_unique_constraint('uq_titles_source_sourceid_mediatype', 'titles', ['source', 'source_id', 'media_type'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_titles_source_id', 'titles', ['source_id'], unique=False)
    op.create_index('ix_titles_source', 'titles', ['source'], unique=False)
    op.create_index('ix_titles_release_year', 'titles', ['release_year'], unique=False)
    op.create_index('ix_titles_media_type', 'titles', ['media_type'], unique=False)
    # ### end Alembic commands ###
