"""titles and watchlist

Revision ID: 7920c84c9c6c
Revises: 9b51e51c5757
Create Date: 2026-01-20 19:43:46.005775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7920c84c9c6c'
down_revision: Union[str, None] = '9b51e51c5757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', 'media_type', name='uq_titles_source_sourceid_mediatype')
    )
    op.create_index(op.f('ix_titles_media_type'), 'titles', ['media_type'], unique=False)
    op.create_index(op.f('ix_titles_release_year'), 'titles', ['release_year'], unique=False)
    op.create_index(op.f('ix_titles_source'), 'titles', ['source'], unique=False)
    op.create_index(op.f('ix_titles_source_id'), 'titles', ['source_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('title_id', sa.UUID(), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='watchlist', nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'title_id', name='uq_watchlist_items_group_title')
    )
    op.create_index(op.f('ix_watchlist_items_added_by_user_id'), 'watchlist_items', ['added_by_user_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_group_id'), 'watchlist_items', ['group_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_snoozed_until'), 'watchlist_items', ['snoozed_until'], unique=False)
    op.create_index(op.f('ix_watchlist_items_status'), 'watchlist_items', ['status'], unique=False)
    op.create_index(op.f('ix_watchlist_items_title_id'), 'watchlist_items', ['title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_title_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_status'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_snoozed_until'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_group_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_added_by_user_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_titles_source_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_source'), table_name='titles')
    op.drop_index(op.f('ix_titles_release_year'), table_name='titles')
    op.drop_index(op.f('ix_titles_media_type'), table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
