"""groups

Revision ID: 9b51e51c5757
Revises: 6dac972dfb54
Create Date: 2026-01-20 10:55:01.767452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b51e51c5757'
down_revision: Union[str, None] = '6dac972dfb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_group_invites_code', 'group_invites', type_='unique')
    op.create_index(op.f('ix_group_invites_code'), 'group_invites', ['code'], unique=True)
    op.create_index(op.f('ix_group_invites_created_by_user_id'), 'group_invites', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_group_invites_expires_at'), 'group_invites', ['expires_at'], unique=False)
    op.create_index(op.f('ix_group_invites_group_id'), 'group_invites', ['group_id'], unique=False)
    op.drop_constraint('group_invites_group_id_fkey', 'group_invites', type_='foreignkey')
    op.create_foreign_key(None, 'group_invites', 'groups', ['group_id'], ['id'])
    op.drop_constraint('uq_group_memberships_group_id_user_id', 'group_memberships', type_='unique')
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    op.create_unique_constraint('uq_group_membership_pair', 'group_memberships', ['group_id', 'user_id'])
    op.drop_constraint('group_memberships_user_id_fkey', 'group_memberships', type_='foreignkey')
    op.drop_constraint('group_memberships_group_id_fkey', 'group_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'group_memberships', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'group_memberships', 'users', ['user_id'], ['id'])
    op.drop_column('group_memberships', 'role')
    op.add_column('groups', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_groups_owner_id'), 'groups', ['owner_id'], unique=False)
    op.drop_constraint('groups_owner_user_id_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'owner_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_owner_user_id_fkey', 'groups', 'users', ['owner_user_id'], ['id'])
    op.drop_index(op.f('ix_groups_owner_id'), table_name='groups')
    op.drop_column('groups', 'owner_id')
    op.add_column('group_memberships', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group_memberships', type_='foreignkey')
    op.drop_constraint(None, 'group_memberships', type_='foreignkey')
    op.create_foreign_key('group_memberships_group_id_fkey', 'group_memberships', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('group_memberships_user_id_fkey', 'group_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_group_membership_pair', 'group_memberships', type_='unique')
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.create_unique_constraint('uq_group_memberships_group_id_user_id', 'group_memberships', ['group_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'group_invites', type_='foreignkey')
    op.create_foreign_key('group_invites_group_id_fkey', 'group_invites', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_group_invites_group_id'), table_name='group_invites')
    op.drop_index(op.f('ix_group_invites_expires_at'), table_name='group_invites')
    op.drop_index(op.f('ix_group_invites_created_by_user_id'), table_name='group_invites')
    op.drop_index(op.f('ix_group_invites_code'), table_name='group_invites')
    op.create_unique_constraint('uq_group_invites_code', 'group_invites', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
